### ISSUE TITLE
Aide à la saisie matches

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4l1#38]
Ajouter 5 boutons de choix d'horaire (14h, 17h, 20h, 20h30 et 21h) en plus des 2 champs Heure et Minutes (qui ne seraient utilisés plus que très rarement pour des horaires autres que les 5 classiques).

**Comment by glideblue7** [comment]
Si celui-ci pouvait être fait en priorité également ;-)

Modification pour le choix d'horaires :+1: 
15h00, 17h00, 19h00, 20h00, 20h45, 21h00

**Comment by johanpoirier** [comment]
J'ai fusionné les 2 issues en une seule
