### ISSUE TITLE
Problème affichage onglets Admin

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4l1#53]
![admin](https://cloud.githubusercontent.com/assets/1861722/18205526/bf59d428-7122-11e6-86c3-ae048689b91b.jpg)

Seconde ligne (celles des onglets admin) quasi invisible

**Comment by johanpoirier** [comment]
Quel navigateur ? sur Chrome c'est bon.

**Comment by johanpoirier** [comment]
OK ça doit être Firefox.

**Comment by johanpoirier** [comment]
OK c'est donc Firefox.

**Comment by glideblue7** [comment]
![admin ie](https://cloud.githubusercontent.com/assets/1861722/18207134/1f6d870e-712a-11e6-86ee-8db03b0c73e7.jpg)
 Et voici pour IE ...

**Comment by glideblue7** [comment]
IE 11.0.9600.18426

**Comment by glideblue7** [comment]
Résolu
