### ISSUE TITLE
Envoi mail désactivé

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4l1#55]
"Recevoir un email de rappel 24H avant le début des matchs si je n'ai pas pronostiqué"

A priori ça ne fonctionne plus depuis la fusion/migration des 2 sites.

**Comment by glideblue7** [comment]
Aurais-tu le temps de réactiver cette fonctionnalité ? De plus en plus de joueurs oublient de pronostiquer ...

**Comment by johanpoirier** [comment]
Ça devrait remarcher normalement.
