### ISSUE TITLE
Mise à jour classement inopérante 

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4l1#63]
Le classement général ne prend pas en compte les derniers résultats, càd les 5 matches de la J18

Pb dû à la succession de 2 journées tronquées ? J17 avec seulement 4 matches suivie de la J18 avec 5 matches.

Pourtant la maj du classement après la J17 à fonctionné. 

Bizarre...

**Comment by johanpoirier** [comment]
J'ai du mal à voir quand ça marche ou pas en fait.
Le premier devrait avoir combien de points ?

**Comment by glideblue7** [comment]
seule la dernière journée en date (J18) n'a pas été prise en compte

chico, le 1er, devrait avoir 108 points, or il a 104, il lui manque bien
les 4 points de la J18

Le ven. 21 déc. 2018 à 17:13, Johan Poirier <notifications@github.com> a
écrit :
